### ISSUE TITLE
Ambari  问题归类

### ISSUE THREAD

**Issue by YohLee** [YohLee/Learning#22]
1.Permission denied: user=dr.who, access=READ_EXECUTE, inode="/warehouse 权限问题
  解决方案有两种，一是直接修改/warehouse 目录的权限设置，操作如下，
/bin/hdfs dfs -chmod -R 755 /tmp
  二是直接修改hdfs的权限配置，建议在测试环境下操作：
      <property>
        <name>dfs.permissions.enabled</name>
        <value>false</value>
    </property>
2.ambari Service 'hdfs' check failed: Server Error，查看日志：
Caused by: org.apache.ambari.server.ClusterNotFoundException: Cluster not found, clusterId=2
at org.apache.ambari.server.state.cluster.ClustersImpl.getCluster(ClustersImpl.java:277)
at org.apache.ambari.server.view.ViewRegistry.getCluster(ViewRegistry.java:928)
… 101 more
出现原因：在新建文件视图之后，对俩个文件视图进行了对比，发现是集群名字跟hdfs配置没有关联起来
解决方案：新建一个文件视图，发现可以成功查看。

**Comment by YohLee** [comment]
hive刷票据

kinit -k -t /etc/security/keytabs/hive.service.keytab hive/node2@KRB.COM
